[package]
name = "FinSc-QuantumComputing"
version = "0.1.0"
authors = ["Justin Kelly"]
description = "Discrete Constructive Quantum Computing, Qubit Circuits, and Entanglement Engine."

[dependencies]
FinSc-Multiset-Core = { path = "../FinSc-Multiset-Core" }
FinSc-Multiset-Transform = { path = "../FinSc-Multiset-Transform" }
FinSc-Geometry = { path = "../FinSc-Geometry" }
idris2-Dihedron = { path = "../FinSc-Dihedron" }
